version: "3.9"

services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "4342:4242"  # SSH access to container
      - "8080:80"    # HTTP access to Nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./torrc:/etc/tor/torrc:ro
    restart: unless-stopped

  tor:
    image: dperson/torproxy
    container_name: tor
    depends_on:
      - nginx
    volumes:
      - tor_hidden:/var/lib/tor/hidden_service
      - ./torrc:/etc/tor/torrc:ro
    restart: unless-stopped

volumes:
  tor_hidden:
