services:
  nginx:
    build: .  # construit l'image Ã  partir de ton Dockerfile
    container_name: nginx
    ports:
      - "4342:4242"  # SSH
      - "8080:80"    # Nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./torrc:/etc/tor/torrc:ro
    restart: unless-stopped

  tor:
    image: dperson/torproxy
    container_name: tor
    depends_on:
      - onion
    restart: unless-stopped