services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "4342:4242"
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  tor:
    build: .
    container_name: tor
    depends_on:
      - nginx
    command: ["/usr/bin/tor", "-f", "/etc/tor/torrc"]
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    restart: unless-stopped
